export const data = {
  links: [
    {
      rel: "first",
      href: "http://localhost/api/cars?page=0&size=9",
      hreflang: null,
      media: null,
      title: null,
      type: null,
      deprecation: null
    },
    {
      rel: "self",
      href: "http://localhost/api/cars{?page,size,sort}",
      hreflang: null,
      media: null,
      title: null,
      type: null,
      deprecation: null
    },
    {
      rel: "next",
      href: "http://localhost/api/cars?page=1&size=9",
      hreflang: null,
      media: null,
      title: null,
      type: null,
      deprecation: null
    },
    {
      rel: "last",
      href: "http://localhost/api/cars?page=31511&size=9",
      hreflang: null,
      media: null,
      title: null,
      type: null,
      deprecation: null
    },
    {
      rel: "profile",
      href: "http://localhost/api/profile/cars",
      hreflang: null,
      media: null,
      title: null,
      type: null,
      deprecation: null
    },
    {
      rel: "search",
      href: "http://localhost/api/cars/search",
      hreflang: null,
      media: null,
      title: null,
      type: null,
      deprecation: null
    }
  ],
  content: [
    {
      configurationid: 1621,
      configurationname: "TGTCatalog",
      userdatabaseid: 29322,
      resourcedatabaseid: 29321,
      databaseid: 29321,
      tgtEntityname1: "AD_)R#!'[o]£<l-{/x&}(%e+1?1$579",
      tgtEntityname2: null,
      tgtEntityname3: null,
      tgtEntitytype: "Provisioning Role",
      tgtEntityowner: null,
      applicationName: null,
      approverRole: null,
      blossomapplicationname: null,
      blossomciid: null,
      catalogCreate: null,
      category: null,
      certifiable: null,
      certifierUser: null,
      complianceClassificationGlba: null,
      complianceClassificationHipa: null,
      complianceClassificationPci: null,
      complianceClassificationSox: null,
      complianceClassSoc1: null,
      entitlementapprovergrouprequir: null,
      entityDescription: null,
      entityDisplayName: null,
      entityName: null,
      entityType: null,
      endpointType: null,
      fulfillmentRole: null,
      highlyprivilegedaccess: null,
      ismanagedaccess: null,
      isDeleted: "1",
      isRequestable: "0",
      isRuleBased: null,
      itemRisk: null,
      managerapprovalrequired: null,
      mlad: null,
      preferredcertmethod: null,
      privilegedaccess: null,
      rcmSource: null,
      resourceType: null,
      scopeDate: null,
      scopeQtr: null,
      triggercertification: null,
      triggerEntitlementCert: null,
      triggerRogue: null,
      triggerUserCert: null,
      userDefinedTags: null,
      catalogUpdate: "2019/08/20 12:40:00.753",
      lastUpdateBy: "CATALOG2.0",
      content: [],
      links: [
        {
          rel: "self",
          href: "http://localhost/api/cars/1",
          hreflang: null,
          media: null,
          title: null,
          type: null,
          deprecation: null
        },
        {
          rel: "tGTCatalog",
          href: "http://localhost/api/cars/1",
          hreflang: null,
          media: null,
          title: null,
          type: null,
          deprecation: null
        }
      ]
    },
    {
      configurationid: 1621,
      configurationname: "TGTCatalog",
      userdatabaseid: 29322,
      resourcedatabaseid: 29321,
      databaseid: 29321,
      tgtEntityname1: "AD_)R#!'[o]£<l-{/x&}(%e+1?1$579",
      tgtEntityname2: null,
      tgtEntityname3: null,
      tgtEntitytype: "Provisioning Role",
      tgtEntityowner: null,
      applicationName: null,
      approverRole: null,
      blossomapplicationname: null,
      blossomciid: null,
      catalogCreate: null,
      category: null,
      certifiable: null,
      certifierUser: null,
      complianceClassificationGlba: null,
      complianceClassificationHipa: null,
      complianceClassificationPci: null,
      complianceClassificationSox: null,
      complianceClassSoc1: null,
      entitlementapprovergrouprequir: null,
      entityDescription: null,
      entityDisplayName: null,
      entityName: null,
      entityType: null,
      endpointType: null,
      fulfillmentRole: null,
      highlyprivilegedaccess: null,
      ismanagedaccess: null,
      isDeleted: "1",
      isRequestable: "0",
      isRuleBased: null,
      itemRisk: null,
      managerapprovalrequired: null,
      mlad: null,
      preferredcertmethod: null,
      privilegedaccess: null,
      rcmSource: null,
      resourceType: null,
      scopeDate: null,
      scopeQtr: null,
      triggercertification: null,
      triggerEntitlementCert: null,
      triggerRogue: null,
      triggerUserCert: null,
      userDefinedTags: null,
      catalogUpdate: "2019/08/20 12:40:00.753",
      lastUpdateBy: "CATALOG2.0",
      content: [],
      links: [
        {
          rel: "self",
          href: "http://localhost/api/cars/1",
          hreflang: null,
          media: null,
          title: null,
          type: null,
          deprecation: null
        },
        {
          rel: "tGTCatalog",
          href: "http://localhost/api/cars/1",
          hreflang: null,
          media: null,
          title: null,
          type: null,
          deprecation: null
        }
      ]
    },
    {
      configurationid: 1621,
      configurationname: "TGTCatalog",
      userdatabaseid: 29322,
      resourcedatabaseid: 29321,
      databaseid: 29321,
      tgtEntityname1: "AD_&Ro/le?179",
      tgtEntityname2: null,
      tgtEntityname3: null,
      tgtEntitytype: "Provisioning Role",
      tgtEntityowner: null,
      applicationName: null,
      approverRole: null,
      blossomapplicationname: null,
      blossomciid: null,
      catalogCreate: null,
      category: null,
      certifiable: null,
      certifierUser: null,
      complianceClassificationGlba: null,
      complianceClassificationHipa: null,
      complianceClassificationPci: null,
      complianceClassificationSox: null,
      complianceClassSoc1: null,
      entitlementapprovergrouprequir: null,
      entityDescription: null,
      entityDisplayName: null,
      entityName: null,
      entityType: null,
      endpointType: null,
      fulfillmentRole: null,
      highlyprivilegedaccess: null,
      ismanagedaccess: null,
      isDeleted: "1",
      isRequestable: "0",
      isRuleBased: null,
      itemRisk: null,
      managerapprovalrequired: null,
      mlad: null,
      preferredcertmethod: null,
      privilegedaccess: null,
      rcmSource: null,
      resourceType: null,
      scopeDate: null,
      scopeQtr: null,
      triggercertification: null,
      triggerEntitlementCert: null,
      triggerRogue: null,
      triggerUserCert: null,
      userDefinedTags: null,
      catalogUpdate: "2019/08/20 12:40:00.753",
      lastUpdateBy: "CATALOG2.0",
      content: [],
      links: [
        {
          rel: "self",
          href: "http://localhost/api/cars/2",
          hreflang: null,
          media: null,
          title: null,
          type: null,
          deprecation: null
        },
        {
          rel: "tGTCatalog",
          href: "http://localhost/api/cars/2",
          hreflang: null,
          media: null,
          title: null,
          type: null,
          deprecation: null
        }
      ]
    },
    {
      configurationid: 1621,
      configurationname: "TGTCatalog",
      userdatabaseid: 29322,
      resourcedatabaseid: 29321,
      databaseid: 29321,
      tgtEntityname1: "AD_&Ro/le?179",
      tgtEntityname2: null,
      tgtEntityname3: null,
      tgtEntitytype: "Provisioning Role",
      tgtEntityowner: null,
      applicationName: null,
      approverRole: null,
      blossomapplicationname: null,
      blossomciid: null,
      catalogCreate: null,
      category: null,
      certifiable: null,
      certifierUser: null,
      complianceClassificationGlba: null,
      complianceClassificationHipa: null,
      complianceClassificationPci: null,
      complianceClassificationSox: null,
      complianceClassSoc1: null,
      entitlementapprovergrouprequir: null,
      entityDescription: null,
      entityDisplayName: null,
      entityName: null,
      entityType: null,
      endpointType: null,
      fulfillmentRole: null,
      highlyprivilegedaccess: null,
      ismanagedaccess: null,
      isDeleted: "1",
      isRequestable: "0",
      isRuleBased: null,
      itemRisk: null,
      managerapprovalrequired: null,
      mlad: null,
      preferredcertmethod: null,
      privilegedaccess: null,
      rcmSource: null,
      resourceType: null,
      scopeDate: null,
      scopeQtr: null,
      triggercertification: null,
      triggerEntitlementCert: null,
      triggerRogue: null,
      triggerUserCert: null,
      userDefinedTags: null,
      catalogUpdate: "2019/08/20 12:40:00.753",
      lastUpdateBy: "CATALOG2.0",
      content: [],
      links: [
        {
          rel: "self",
          href: "http://localhost/api/cars/2",
          hreflang: null,
          media: null,
          title: null,
          type: null,
          deprecation: null
        },
        {
          rel: "tGTCatalog",
          href: "http://localhost/api/cars/2",
          hreflang: null,
          media: null,
          title: null,
          type: null,
          deprecation: null
        }
      ]
    },
    {
      configurationid: 1621,
      configurationname: "TGTCatalog",
      userdatabaseid: 29322,
      resourcedatabaseid: 29321,
      databaseid: 29321,
      tgtEntityname1: "SAP_PCC_CAMPAIGN_MANAGER_50.1",
      tgtEntityname2: "SAP R3[EP]QCMCLNT100",
      tgtEntityname3:
        "SAPRole[P]SAPRole=SAP_PCC_CAMPAIGN_MANAGER_50.1,SAPRoleContainer=SAP roles,EndPoint=QCMCLNT100,Namespace=SAP R3,Domain=im,Server=Server",
      tgtEntitytype: null,
      tgtEntityowner: null,
      applicationName: null,
      approverRole: null,
      blossomapplicationname: null,
      blossomciid: null,
      catalogCreate: "2019/08/20 12:15:00.091",
      category: "Entitlement",
      certifiable: "0",
      certifierUser: null,
      complianceClassificationGlba: null,
      complianceClassificationHipa: null,
      complianceClassificationPci: null,
      complianceClassificationSox: null,
      complianceClassSoc1: null,
      entitlementapprovergrouprequir: null,
      entityDescription: null,
      entityDisplayName: "ServiceNow-QA-TEST2",
      entityName: "ServiceNow-QA-TEST2",
      entityType: "Entitlement",
      endpointType: null,
      fulfillmentRole: null,
      highlyprivilegedaccess: null,
      ismanagedaccess: null,
      isDeleted: "0",
      isRequestable: "0",
      isRuleBased: null,
      itemRisk: null,
      managerapprovalrequired: null,
      mlad: "FALSE",
      preferredcertmethod: null,
      privilegedaccess: null,
      rcmSource: null,
      resourceType: null,
      scopeDate: null,
      scopeQtr: null,
      triggercertification: null,
      triggerEntitlementCert: null,
      triggerRogue: null,
      triggerUserCert: null,
      userDefinedTags: null,
      catalogUpdate: "2019/08/20 13:36:51.519",
      lastUpdateBy: "Catalog2.0",
      content: [],
      links: [
        {
          rel: "self",
          href: "http://localhost/api/cars/3",
          hreflang: null,
          media: null,
          title: null,
          type: null,
          deprecation: null
        },
        {
          rel: "tGTCatalog",
          href: "http://localhost/api/cars/3",
          hreflang: null,
          media: null,
          title: null,
          type: null,
          deprecation: null
        }
      ]
    },
    {
      configurationid: 1621,
      configurationname: "TGTCatalog",
      userdatabaseid: 29322,
      resourcedatabaseid: 29321,
      databaseid: 29321,
      tgtEntityname1: "SAP_PCC_CAMPAIGN_MANAGER_50.1",
      tgtEntityname2: "SAP R3[EP]QCMCLNT100",
      tgtEntityname3:
        "SAPRole[P]SAPRole=SAP_PCC_CAMPAIGN_MANAGER_50.1,SAPRoleContainer=SAP roles,EndPoint=QCMCLNT100,Namespace=SAP R3,Domain=im,Server=Server",
      tgtEntitytype: null,
      tgtEntityowner: null,
      applicationName: null,
      approverRole: null,
      blossomapplicationname: null,
      blossomciid: null,
      catalogCreate: "2019/08/20 12:15:00.091",
      category: "Entitlement",
      certifiable: "0",
      certifierUser: null,
      complianceClassificationGlba: null,
      complianceClassificationHipa: null,
      complianceClassificationPci: null,
      complianceClassificationSox: null,
      complianceClassSoc1: null,
      entitlementapprovergrouprequir: null,
      entityDescription: null,
      entityDisplayName: "ServiceNow-QA-TEST2",
      entityName: "ServiceNow-QA-TEST2",
      entityType: "Entitlement",
      endpointType: null,
      fulfillmentRole: null,
      highlyprivilegedaccess: null,
      ismanagedaccess: null,
      isDeleted: "0",
      isRequestable: "0",
      isRuleBased: null,
      itemRisk: null,
      managerapprovalrequired: null,
      mlad: "FALSE",
      preferredcertmethod: null,
      privilegedaccess: null,
      rcmSource: null,
      resourceType: null,
      scopeDate: null,
      scopeQtr: null,
      triggercertification: null,
      triggerEntitlementCert: null,
      triggerRogue: null,
      triggerUserCert: null,
      userDefinedTags: null,
      catalogUpdate: "2019/08/20 13:36:51.519",
      lastUpdateBy: "Catalog2.0",
      content: [],
      links: [
        {
          rel: "self",
          href: "http://localhost/api/cars/3",
          hreflang: null,
          media: null,
          title: null,
          type: null,
          deprecation: null
        },
        {
          rel: "tGTCatalog",
          href: "http://localhost/api/cars/3",
          hreflang: null,
          media: null,
          title: null,
          type: null,
          deprecation: null
        }
      ]
    },
    {
      configurationid: 1621,
      configurationname: "TGTCatalog",
      userdatabaseid: 29322,
      resourcedatabaseid: 29321,
      databaseid: 29321,
      tgtEntityname1: "AD_@Ro$le3279",
      tgtEntityname2: null,
      tgtEntityname3: null,
      tgtEntitytype: "Provisioning Role",
      tgtEntityowner: null,
      applicationName: null,
      approverRole: null,
      blossomapplicationname: null,
      blossomciid: null,
      catalogCreate: null,
      category: null,
      certifiable: null,
      certifierUser: null,
      complianceClassificationGlba: null,
      complianceClassificationHipa: null,
      complianceClassificationPci: null,
      complianceClassificationSox: null,
      complianceClassSoc1: null,
      entitlementapprovergrouprequir: null,
      entityDescription: null,
      entityDisplayName: null,
      entityName: null,
      entityType: null,
      endpointType: null,
      fulfillmentRole: null,
      highlyprivilegedaccess: null,
      ismanagedaccess: null,
      isDeleted: "1",
      isRequestable: "0",
      isRuleBased: null,
      itemRisk: null,
      managerapprovalrequired: null,
      mlad: null,
      preferredcertmethod: null,
      privilegedaccess: null,
      rcmSource: null,
      resourceType: null,
      scopeDate: null,
      scopeQtr: null,
      triggercertification: null,
      triggerEntitlementCert: null,
      triggerRogue: null,
      triggerUserCert: null,
      userDefinedTags: null,
      catalogUpdate: "2019/08/20 12:40:00.753",
      lastUpdateBy: "CATALOG2.0",
      content: [],
      links: [
        {
          rel: "self",
          href: "http://localhost/api/cars/4",
          hreflang: null,
          media: null,
          title: null,
          type: null,
          deprecation: null
        },
        {
          rel: "tGTCatalog",
          href: "http://localhost/api/cars/4",
          hreflang: null,
          media: null,
          title: null,
          type: null,
          deprecation: null
        }
      ]
    },
    {
      configurationid: 1621,
      configurationname: "TGTCatalog",
      userdatabaseid: 29322,
      resourcedatabaseid: 29321,
      databaseid: 29321,
      tgtEntityname1: "AD_@Ro$le3279",
      tgtEntityname2: null,
      tgtEntityname3: null,
      tgtEntitytype: "Provisioning Role",
      tgtEntityowner: null,
      applicationName: null,
      approverRole: null,
      blossomapplicationname: null,
      blossomciid: null,
      catalogCreate: null,
      category: null,
      certifiable: null,
      certifierUser: null,
      complianceClassificationGlba: null,
      complianceClassificationHipa: null,
      complianceClassificationPci: null,
      complianceClassificationSox: null,
      complianceClassSoc1: null,
      entitlementapprovergrouprequir: null,
      entityDescription: null,
      entityDisplayName: null,
      entityName: null,
      entityType: null,
      endpointType: null,
      fulfillmentRole: null,
      highlyprivilegedaccess: null,
      ismanagedaccess: null,
      isDeleted: "1",
      isRequestable: "0",
      isRuleBased: null,
      itemRisk: null,
      managerapprovalrequired: null,
      mlad: null,
      preferredcertmethod: null,
      privilegedaccess: null,
      rcmSource: null,
      resourceType: null,
      scopeDate: null,
      scopeQtr: null,
      triggercertification: null,
      triggerEntitlementCert: null,
      triggerRogue: null,
      triggerUserCert: null,
      userDefinedTags: null,
      catalogUpdate: "2019/08/20 12:40:00.753",
      lastUpdateBy: "CATALOG2.0",
      content: [],
      links: [
        {
          rel: "self",
          href: "http://localhost/api/cars/4",
          hreflang: null,
          media: null,
          title: null,
          type: null,
          deprecation: null
        },
        {
          rel: "tGTCatalog",
          href: "http://localhost/api/cars/4",
          hreflang: null,
          media: null,
          title: null,
          type: null,
          deprecation: null
        }
      ]
    },
    {
      configurationid: 1621,
      configurationname: "TGTCatalog",
      userdatabaseid: 29322,
      resourcedatabaseid: 29321,
      databaseid: 29321,
      tgtEntityname1: "AD_&Ro/le?4279",
      tgtEntityname2: null,
      tgtEntityname3: null,
      tgtEntitytype: "Provisioning Role",
      tgtEntityowner: null,
      applicationName: null,
      approverRole: null,
      blossomapplicationname: null,
      blossomciid: null,
      catalogCreate: null,
      category: null,
      certifiable: null,
      certifierUser: null,
      complianceClassificationGlba: null,
      complianceClassificationHipa: null,
      complianceClassificationPci: null,
      complianceClassificationSox: null,
      complianceClassSoc1: null,
      entitlementapprovergrouprequir: null,
      entityDescription: null,
      entityDisplayName: null,
      entityName: null,
      entityType: null,
      endpointType: null,
      fulfillmentRole: null,
      highlyprivilegedaccess: null,
      ismanagedaccess: null,
      isDeleted: "1",
      isRequestable: "0",
      isRuleBased: null,
      itemRisk: null,
      managerapprovalrequired: null,
      mlad: null,
      preferredcertmethod: null,
      privilegedaccess: null,
      rcmSource: null,
      resourceType: null,
      scopeDate: null,
      scopeQtr: null,
      triggercertification: null,
      triggerEntitlementCert: null,
      triggerRogue: null,
      triggerUserCert: null,
      userDefinedTags: null,
      catalogUpdate: "2019/08/20 12:40:00.753",
      lastUpdateBy: "CATALOG2.0",
      content: [],
      links: [
        {
          rel: "self",
          href: "http://localhost/api/cars/5",
          hreflang: null,
          media: null,
          title: null,
          type: null,
          deprecation: null
        },
        {
          rel: "tGTCatalog",
          href: "http://localhost/api/cars/5",
          hreflang: null,
          media: null,
          title: null,
          type: null,
          deprecation: null
        }
      ]
    }
  ],
  page: {
    size: 9,
    totalElements: 283608,
    totalPages: 31512,
    number: 0
  }
};
